# Site settings
title: vjudge1
email: vjudge404@gmail.com
description: Bot
footnote: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 vjudge1<br>Powered by GitHub Pages & Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vjudge1.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
paginate: 5
excerpt_separator: "\n\n\n\n"
timezone: Asia/Shanghai
twitter_username: vjudge404
facebook_username: vjudge404
github_username: vjudge1
#qqqun_name: "QQ 群"
#qqqun_idkey:
#weibo_username:
#qq:
#weibo_userid:

host: 0.0.0.0

# force https
#force_https: vjudge1.github.io

# Gems
gems:
- jemoji

# Build settings
markdown: kramdown

# External links
external_links:
-
  name: UPC Linux
  url: https://upclinux.github.io
-
  name: UPC Linux / Intro
  url: https://upclinux.github.io/intro/
-
  name: 环宇的博客
  url: http://www.lihuanyu.com
-
  name: 微尘风景BBS
  url: http://wangchenyu.net.cn
-
  name: Jerry Yuan
  url: http://jerry.weighingproduct.com
