# Site settings
title: vjudge1
email: vjudge404@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Just a test.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vjudge1.github.io" # the base hostname & protocol for your site
twitter_username: vjudge404
github_username:  vjudge1

# Build settings
markdown: kramdown
