# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Site settings
title: Unorz
email: vjudge404@gmail.com
description: Doubleplusorz...
footnote: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 vjudge1
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vjudge1.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
paginate: 5
excerpt_separator: "\n\n\n\n"
timezone: Asia/Shanghai
twitter_username: vjudge404
facebook_username: vjudge404
github_username: vjudge1
brand: >
  <i class="fa fa-github-alt"></i> Unorz
#qqqun_name: "QQ 群"
#qqqun_idkey:
#weibo_username:
#qq:
#weibo_userid:

host: 0.0.0.0

# force https
force_https: vjudge1.github.io

# Gems
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate

# Build settings
markdown: kramdown

# External links
external_links:
-
  name: UPC Linux
  url: https://upclinux.github.io
-
  name: UPC Linux / Intro
  url: https://upclinux.github.io/intro/
-
  name: 环宇的博客
  url: http://www.lihuanyu.com
-
  name: 微尘风景BBS
  url: http://wangchenyu.net.cn
-
  name: Jerry Yuan
  url: http://jerry.weighingproduct.com

# Footer List
footer_links:
-
  name: About
  url: /about/
-
  name: 让我帮你百度一下
  url: https://vjudge1.github.io/kuso/sos/
